[package]
build = "../swarmy-store/build.rs"
name = "swarmy-volume"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

# Only kernel.rs opts into unsafe code for Linux NBD ioctls.
[lints]
workspace = true

[dependencies]
async-trait.workspace = true
swarmy-core.workspace = true
swarmy-store.workspace = true
jiff.workspace = true
object_store.workspace = true
blake3.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

tokio.workspace = true
tracing.workspace = true
fs2.workspace = true
libc.workspace = true
ulid.workspace = true
futures.workspace = true
toml.workspace = true
tempfile.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
