[package]
name = "swarmy-harness"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures.workspace = true
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
swarmy-core.workspace = true
swarmy-llm.workspace = true

[dev-dependencies]
tokio.workspace = true
ulid.workspace = true
