[package]
name = "swarmy-config"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
object_store.workspace = true
tracing.workspace = true
swarmy-core.workspace = true
ulid.workspace = true
fs2.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
shell-words.workspace = true

[dev-dependencies]
tempfile.workspace = true
