[package]
name = "swarmy-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "swarmy"
path = "src/main.rs"

[dependencies]
ratatui.workspace = true
crossterm.workspace = true
unicode-width.workspace = true
futures-util.workspace = true
fs2.workspace = true
rustix.workspace = true
swarmy-config.workspace = true
clap.workspace = true
swarmy-core.workspace = true
anyhow.workspace = true
serde_json.workspace = true
swarmy-llm.workspace = true
tokio.workspace = true
swarmy-bus.workspace = true
swarmy-store.workspace = true
jiff.workspace = true
ulid.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
portable-pty.workspace = true
vt100.workspace = true
tempfile.workspace = true
async-nats.workspace = true
foundationdb.workspace = true
