[package]
build = "../swarmy-store/build.rs"
name = "swarmy-gateway"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
swarmy-api-types.workspace = true
async-trait.workspace = true
thiserror.workspace = true
swarmy-version.workspace = true
swarmy-config.workspace = true
anyhow.workspace = true
async-stream.workspace = true
futures.workspace = true
jiff.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
swarmy-bus.workspace = true
swarmy-core.workspace = true
swarmy-llm.workspace = true
swarmy-harness.workspace = true
blake3.workspace = true
swarmy-store.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ulid.workspace = true

[dev-dependencies]
wiremock.workspace = true
async-nats.workspace = true
foundationdb.workspace = true
tempfile.workspace = true
